#
# MusterCull
# Bukkit plug-in default configuration file.
#

#limits:
#- type: CREEPER
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SKELETON
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SPIDER
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: ZOMBIE
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SLIME
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: GHAST
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: PIGZOMBIE
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: ENDERMAN
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: CAVESPIDER
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SILVERFISH
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: BLAZE
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: LAVASLIME
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: ENDERDRAGON
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: PIG
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SHEEP
#  limit: 6
#  culling: SPAWN
#  range: 0
#- type: COW
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: CHICKEN
#  limit: 12
#  culling: SPAWN
#  range: 0
#- type: SQUID
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: WOLF
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: MUSHROOMCOW
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: SNOWMAN
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: OZELOT
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: VILLAGERGOLEM
#  limit: 0
#  culling: SPAWN
#  range: 0
#- type: VILLAGER
#  limit: 0
#  culling: SPAWN
#  range: 0

# The amount of damage to apply to mobs which are considered crowded under the
# DAMAGE method of culling.
damage: 6

# The percent chance that a mob will be damaged if crowded under the DAMAGE
# method of culling.
damage_chance: 75

# The number of ticks between invocations of the damage method for mobs.
ticks_between_damage: 10

# The number of entities to damage each round of the laborer.
damage_count: 1

# The maximum number of living entities allowed to be loaded.
mob_max_mob: 10000

# mob_player_multiplier is multiplied by the number of online players.
# This number of how much smaller the mob cap is than mob_max_mob.
mob_player_multiplier: 5

# The number of ticks between invocations of the hardcap laborer for mobs.
ticks_between_hard_cap: 40

